### ISSUE TITLE
Burning DTC for promo

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/avalon#78]
I burnt 5 DTC, though it doesn't seem to have much effect. I'm not sure what the formula is for determining how big a boost you're going to get for burning DTC, but I feel as though it's a big ask.

The reason I say this is, with burning 5, I can't tell that any significant change has happened because of it. For me, idc, but for the end users I think they would.

Suggesting:

- Rework the burn DTC option to be a little more powerful (and hopefully scale with inflation so we don't have to fix this again)

**Comment by techcoderx** [comment]
The burn basically adds more VP to the first vote, giving it more visibility from the beginning. At current chain config 1 DTUBE burn converts to 4,400 VP, 6 months equivalent of VP generation. Hence, 5 DTUBE adds 22,000 VP to the first vote.

The same config will be used to convert 50% of the burn amount to pre-loaded VP for new account creation after HF4 activation.

At the current state an increase is not really needed as there will be zero net inflation for over a year due to the periodic burn that will take place every 9,600 blocks after HF4. But I wouldn't mind that if more VP gets used overall.

**Comment by DevDeckardCain** [comment]
> The burn basically adds more VP to the first vote, giving it more visibility from the beginning. At current chain config 1 DTUBE burn converts to 4,400 VP, 6 months equivalent of VP generation. Hence, 5 DTUBE adds 22,000 VP to the first vote.
> 
> The same config will be used to convert 50% of the burn amount to pre-loaded VP for new account creation after HF4 activation.
> 
> At the current state an increase is not really needed as there will be zero net inflation for over a year due to the periodic burn that will take place every 9,600 blocks after HF4. But I wouldn't mind that if more VP gets used overall.

6 Months eh... From a user standpoint I feel like I didn't get much, but 6 months is a lot... From what you've said, I'm going to assume that this is all flat then (no parabolic curve; eg, right now 1DTC = 4.4K and is worth around $.18EA, should this price jump to $1EA, it would still be 4.4k).

The first idea that comes to mind is to set it up so that presently you burn more, but in the future you would have to burn less to achieve the same VP.

**Comment by techcoderx** [comment]
`vtPerBurn` may now be changed through governance, please submit a chain update proposal to change VP per burn amounts.
